### ISSUE TITLE
123

### ISSUE THREAD

**Issue by mengpengfei** [dlunion/CC5.0#9]

**Comment by 1694439208** [comment]
在现实中，我忍气吞声，不敢侮辱别人，在网络上，我重拳出击，辱骂网友，意气风发！天不生我键盘侠，喷道万古如长夜。仙之巅，傲世间，有我键盘侠就有天，大河之键天上来，键来！！！

**Comment by qaz734913414** [comment]
别人开源出来就是无私奉献的精神，你这种喷子有本事自己开源一个啊，自己不会配置使用怪别人开源不好，真废物！

**Comment by Chordp** [comment]
在现实中，我忍气吞声，不敢侮辱别人，在网络上，我重拳出击，辱骂网友，意气风发！天不生我键盘侠，喷道万古如长夜。仙之巅，傲世间，有我键盘侠就有天，大河之键天上来，键来！！！

**Comment by yiran-THU** [comment]
慕名而来，围观奇葩

**Comment by leng-yue** [comment]
在现实中，我忍气吞声，不敢侮辱别人，在网络上，我重拳出击，辱骂网友，意气风发！天不生我键盘侠，喷道万古如长夜。仙之巅，傲世间，有我键盘侠就有天，大河之键天上来，键来！！！

**Comment by maoxiaosc** [comment]
hope大神不会在意这些评论的

**Comment by ChHanXiao** [comment]
惊呆了，围观

**Comment by ycdhqzhiai** [comment]
真是奇葩中的奇葩，怎么什么人都有啊

**Comment by pango99** [comment]
我是来看别人怎么骂你的 @

**Comment by BaofengZan** [comment]
都能跑啊，技术不过关还在这bibi。
